# Generated by Django 5.0.6 on 2024-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('headerimg', models.ImageField(null=True, upload_to='ads/')),
                ('whatsnewimg', models.ImageField(null=True, upload_to='ads/')),
                ('mostpopularimg', models.ImageField(null=True, upload_to='ads/')),
                ('endpageimg', models.ImageField(null=True, upload_to='ads/')),
                ('footerimg', models.ImageField(null=True, upload_to='ads/')),
                ('detailsimg', models.ImageField(null=True, upload_to='ads/')),
            ],
        ),
    ]
