# Generated by Django 5.0.6 on 2024-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
