# Generated by Django 5.0.6 on 2024-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_ads_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='SysLogo')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('slogan', models.TextField()),
                ('facebooklink', models.URLField(null=True)),
                ('youtubelink', models.URLField(null=True)),
            ],
        ),
    ]
