# Generated by Django 5.0.6 on 2024-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='facebooklink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='youtubelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
