# Generated by Django 5.0.6 on 2024-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='user@user.com', max_length=254),
        ),
    ]
