# Generated by Django 5.0.6 on 2024-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_ads_detailsimg_remove_ads_endpageimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_type',
            field=models.CharField(choices=[('headerimg', 'Headerimg'), ('whatnewimage', 'WhatsNewImage'), ('mostpopularimg', 'MostPopularImg'), ('endpageimg', 'EndPageimg'), ('footerimg', 'FooTerimg'), ('detailsimg', 'Detailsimg')], default='whatnewimage', max_length=200),
        ),
    ]
