# Generated by Django 5.0.6 on 2024-07-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_ads_image_height_remove_ads_image_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=60)),
                ('proff', models.CharField(max_length=50)),
            ],
        ),
    ]
